SHELL = /bin/bash
ifeq ($(PARAM_FILE), )
	PARAM_FILE:=../../../../../$(shell echo $(MW_VER))/Makefile.param
	include $(PARAM_FILE)
endif

RELEASE_FOLDER = $(PWD)/bin

TARGET_A = $(MW_LIB)/libraw_replay.a
TARGET_SO = $(MW_LIB)/libraw_replay.so

.PHONY: all clean
.SILENT: all clean

all:
	@cp -f libraw_replay.a $(MW_LIB)
	@cp -f libraw_replay.so $(MW_LIB)

clean:
	@rm -f $(TARGET_A) $(TARGET_SO)

