#ifndef _CVI_TDL_APP_FACE_CAPTURE_DEFAULT_CONFIG_H_
#define _CVI_TDL_APP_FACE_CAPTURE_DEFAULT_CONFIG_H_

#define SIZE_MIN_THRESHOLD 32
#define SIZE_MAX_THRESHOLD 512
#define QUALITY_ASSESSMENT_METHOD AREA_RATIO
#define QUALITY_THRESHOLD 0.1
#define QUALITY_HIGH_THRESHOLD 0.99
#define MISS_TIME_LIMIT 40
#define FAST_MODE_INTERVAL 20
#define FAST_MODE_CAPTURE_NUM 3
#define CYCLE_MODE_INTERVAL 20
#define AUTO_MODE_TIME_LIMIT 0

#endif