#ifndef _CVI_TDL_APP_PERSON_CAPTURE_DEFAULT_CONFIG_H_
#define _CVI_TDL_APP_PERSON_CAPTURE_DEFAULT_CONFIG_H_

#define THRESHOLD_AREA_BASE (480 * 240)
#define THRESHOLD_AREA_MIN (128 * 64)
#define THRESHOLD_AREA_MAX (720 * 360)
#define THRESHOLD_ASPECT_RATIO_MIN 1.0
#define THRESHOLD_ASPECT_RATIO_MAX 3.0
#define QUALITY_THRESHOLD 0.8
#define MISS_TIME_LIMIT 40
#define FAST_MODE_INTERVAL 20
#define FAST_MODE_CAPTURE_NUM 3
#define CYCLE_MODE_INTERVAL 20
#define AUTO_MODE_TIME_LIMIT 0

#endif