DUO_WIRINGX_VERSION = 1.0.3
DUO_WIRINGX_SITE = $(call github,milkv-duo,duo-wiringx,$(DUO_WIRINGX_VERSION))
DUO_WIRINGX_LICENSE = MPL-2.0
DUO_WIRINGX_LICENSE_FILES = COPYING
DUO_WIRINGX_INSTALL_STAGING = YES

$(eval $(cmake-package))
